name = "Vanilla+ ServerMinimal"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e369f134bf84e20d6782de6b0692187cbf4b5e26d42c1ae171be56b9c68a7b1"

[versions]
fabric = "0.12.12"
minecraft = "1.16.5"
