name = "Fabulously Optimized"
version = "1.12.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba77dfc466f36b8408c15b564a6a326f447e6f308adf16a0bab1f99195055389"

[versions]
fabric = "0.12.12"
minecraft = "1.16.5"
