name = "Vanilla+ ServerMinimal"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e6c8fde6cef905de43eb1adc61c4fd5f38c0b5a761a57e30bba1bca670bfced0"

[versions]
fabric = "0.12.12"
minecraft = "1.16.5"
