name = "Fabulously Optimized"
version = "1.12.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2eecdd4e3346740851199dfa188a2187001a5ebc6695ef2a8e8a746657b98171"

[versions]
fabric = "0.12.12"
minecraft = "1.16.5"
