name = "Vanilla+ ServerMinimal"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7435a817110c29b7d58c0a528923336ebc362616afa65eab71cea64162284add"

[versions]
fabric = "0.12.12"
minecraft = "1.16.5"
