[RSDungeonsConfig]
addDungeonsToModdedBiomes = true
blacklistedDungeonBiomes = ""

[RSDungeonsConfig.attemptsPerChunk]
badlandsDungeonAttemptsPerChunk = 8
darkForestDungeonAttemptsPerChunk = 8
desertDungeonAttemptsPerChunk = 8
jungleDungeonAttemptsPerChunk = 8
mushroomDungeonAttemptsPerChunk = 8
snowDungeonAttemptsPerChunk = 8
icyDungeonAttemptsPerChunk = 8
swampDungeonAttemptsPerChunk = 8
endDungeonAttemptsPerChunk = 12
netherDungeonAttemptsPerChunk = 12
oceanDungeonAttemptsPerChunk = 5

[RSDungeonsConfig.minHeight]
badlandsDungeonMinHeight = 2
darkForestDungeonMinHeight = 2
desertDungeonMinHeight = 2
jungleDungeonMinHeight = 2
mushroomDungeonMinHeight = 2
snowDungeonMinHeight = 2
icyDungeonMinHeight = 2
swampDungeonMinHeight = 2
endDungeonMinHeight = 2
netherDungeonMinHeight = 2
oceanDungeonMinHeight = 3

[RSDungeonsConfig.maxHeight]
badlandsDungeonMaxHeight = 255
darkForestDungeonMaxHeight = 255
desertDungeonMaxHeight = 255
jungleDungeonMaxHeight = 255
mushroomDungeonMaxHeight = 255
snowDungeonMaxHeight = 255
icyDungeonMaxHeight = 255
swampDungeonMaxHeight = 255
endDungeonMaxHeight = 255
netherDungeonMaxHeight = 255
oceanDungeonMaxHeight = 255
[RSMainConfig]
blacklistedDimensions = "the_bumblezone:the_bumblezone,the_aether:the_aether"
importModdedItems = true
blacklistedRSLoottablesFromImportingModdedItems = ""

[RSMainConfig.jungleFortress]
jungleFortressMaxChunkDistance = 50
addJungleFortressToModdedBiomes = true
blacklistedFortressBiomes = ""
jungleFortressSize = 10
jungleFortressMinHeight = 56
jungleFortressMaxHeight = 63
jungleFortressVerticalRange = 33

[RSMainConfig.igloos]
blacklistedIglooBiomes = ""
grassyIglooMaxChunkDistance = 20
addGrassyIglooToModdedBiomes = true
stoneIglooMaxChunkDistance = 20
addStoneIglooToModdedBiomes = true

[RSMainConfig.ruinedPortals]
blacklistedRuinedPortalsBiomes = ""
addRuinedPortalEndToModdedBiomes = true
ruinedPortalEndMaxChunkDistance = 57

[RSMainConfig.ruins]
blacklistedRuinsBiomes = ""
addRuinsNetherToModdedBiomes = true
ruinsNetherMaxChunkDistance = 35
addRuinsLandWarmToModdedBiomes = true
ruinsLandWarmMaxChunkDistance = 36
addRuinsLandHotToModdedBiomes = true
ruinsLandHotMaxChunkDistance = 39

[RSMainConfig.cities]
blacklistedCitiesBiomes = ""
addCityNetherToModdedBiomes = true
cityNetherMaxChunkDistance = 120
[RSTemplesConfig.temples]
blacklistedTempleBiomes = ""
netherWastelandTempleMaxChunkDistance = 27
addNetherWastelandTempleToModdedBiomes = false
netherBasaltTempleMaxChunkDistance = 27
addNetherBasaltTempleToModdedBiomes = false
netherCrimsonTempleMaxChunkDistance = 27
addNetherCrimsonTempleToModdedBiomes = false
netherWarpedTempleMaxChunkDistance = 27
addNetherWarpedTempleToModdedBiomes = false
netherSoulTempleMaxChunkDistance = 27
addNetherSoulTempleToModdedBiomes = false
[RSTemplesConfig.pyramids]
blacklistedPyramidBiomes = ""
netherPyramidMaxChunkDistance = 37
addNetherPyramidToModdedBiomes = true
badlandsPyramidMaxChunkDistance = 40
addBadlandsPyramidToModdedBiomes = true
pyramidSnowyMaxChunkDistance = 40
addPyramidSnowyToModdedBiomes = true
pyramidEndMaxChunkDistance = 68
addPyramidEndToModdedBiomes = true
pyramidIcyMaxChunkDistance = 37
addPyramidIcyToModdedBiomes = true
pyramidJungleMaxChunkDistance = 44
addPyramidJungleToModdedBiomes = true
pyramidMushroomMaxChunkDistance = 24
addPyramidMushroomToModdedBiomes = true
pyramidOceanMaxChunkDistance = 40
addPyramidOceanToModdedBiomes = true
addPyramidGiantTreeTaigaToModdedBiomes = true
pyramidGiantTreeTaigaMaxChunkDistance = 40
addPyramidFlowerForestToModdedBiomes = true
pyramidFlowerForestMaxChunkDistance = 36
[RSMineshaftsConfig]
lootChestsMS = true
addMineshaftsToModdedBiomes = true
blacklistedMineshaftBiomes = "betterend:sulphur_springs"

[RSMineshaftsConfig.spawnrate]
birchMineshaftSpawnrate = 40
jungleMineshaftSpawnrate = 40
desertMineshaftSpawnrate = 40
stoneMineshaftSpawnrate = 40
savannaMineshaftSpawnrate = 40
icyMineshaftSpawnrate = 40
oceanMineshaftSpawnrate = 40
taigaMineshaftSpawnrate = 40
swampMineshaftSpawnrate = 40
darkForestMineshaftSpawnrate = 40
endMineshaftSpawnrate = 60
netherMineshaftSpawnrate = 40
crimsonMineshaftSpawnrate = 40
warpedMineshaftSpawnrate = 40

[RSMineshaftsConfig.minHeight]
birchMineshaftMinHeight = 8
jungleMineshaftMinHeight = 8
desertMineshaftMinHeight = 8
stoneMineshaftMinHeight = 8
savannaMineshaftMinHeight = 8
icyMineshaftMinHeight = 8
oceanMineshaftMinHeight = 8
taigaMineshaftMinHeight = 8
swampMineshaftMinHeight = 8
darkForestMineshaftMinHeight = 8
endMineshaftMinHeight = 30
netherMineshaftMinHeight = 6
crimsonMineshaftMinHeight = 6
warpedMineshaftMinHeight = 6

[RSMineshaftsConfig.maxHeight]
birchMineshaftMaxHeight = 45
jungleMineshaftMaxHeight = 45
desertMineshaftMaxHeight = 45
stoneMineshaftMaxHeight = 45
savannaMineshaftMaxHeight = 45
icyMineshaftMaxHeight = 45
oceanMineshaftMaxHeight = 26
taigaMineshaftMaxHeight = 45
swampMineshaftMaxHeight = 45
darkForestMineshaftMaxHeight = 45
endMineshaftMaxHeight = 40
netherMineshaftMaxHeight = 17
crimsonMineshaftMaxHeight = 14
warpedMineshaftMaxHeight = 14

[RSMineshaftsConfig.size]
birchMineshaftSize = 9
jungleMineshaftSize = 9
desertMineshaftSize = 9
stoneMineshaftSize = 9
savannaMineshaftSize = 9
icyMineshaftSize = 9
oceanMineshaftSize = 9
taigaMineshaftSize = 9
swampMineshaftSize = 9
darkForestMineshaftSize = 9
endMineshaftSize = 11
netherMineshaftSize = 10
crimsonMineshaftSize = 10
warpedMineshaftSize = 10

[RSMineshaftsConfig.misc]
barrensIslandsEndMineshafts = false
[RSStrongholdsConfig]
blacklistedStrongholdBiomes = ""

[RSStrongholdsConfig.nether]
netherStrongholdSize = 15
netherStrongholdMaxChunkDistance = 100
addNetherStrongholdToModdedBiomes = true
netherStrongholdMinHeight = 6
netherStrongholdMaxHeight = 36
[RSOutpostsConfig]
blacklistedOutpostBiomes = ""

[RSOutpostsConfig.outposts]
netherBrickOutpostMaxChunkDistance = 34
addNetherBrickOutpostToModdedBiomes = true
warpedOutpostMaxChunkDistance = 34
addWarpedOutpostToModdedBiomes = true
crimsonOutpostMaxChunkDistance = 34
addCrimsonOutpostToModdedBiomes = true
addOutpostBirchToModdedBiomes = true
outpostBirchMaxChunkDistance = 45
addOutpostJungleToModdedBiomes = true
outpostJungleMaxChunkDistance = 45
addOutpostGiantTreeTaigaToModdedBiomes = true
outpostGiantTreeTaigaMaxChunkDistance = 45
addOutpostDesertToModdedBiomes = true
outpostDesertMaxChunkDistance = 45
addOutpostBadlandsToModdedBiomes = true
outpostBadlandsMaxChunkDistance = 45
addOutpostSnowyToModdedBiomes = true
outpostSnowyMaxChunkDistance = 45
addOutpostIcyToModdedBiomes = true
outpostIcyMaxChunkDistance = 41
addOutpostTaigaToModdedBiomes = true
outpostTaigaMaxChunkDistance = 45
addOutpostOakToModdedBiomes = true
outpostOakMaxChunkDistance = 45
outpostEndMaxChunkDistance = 61
addOutpostEndToModdedBiomes = true
[RSVillagesConfig]
addVillagesToModdedBiomes = true
blacklistedVillageBiomes = ""
badlandsVillageMaxChunkDistance = 30
birchVillageMaxChunkDistance = 38
darkForestVillageMaxChunkDistance = 38
jungleVillageMaxChunkDistance = 38
swampVillageMaxChunkDistance = 38
mountainsVillageMaxChunkDistance = 38
giantTaigaVillageMaxChunkDistance = 38
crimsonVillageMaxChunkDistance = 30
warpedVillageMaxChunkDistance = 30
villageOakMaxChunkDistance = 38
[RSWellsConfig]
addWellsToModdedBiomes = true
blacklistedWellBiomes = ""
canHaveBells = true

[RSWellsConfig.rarityPerChunk]
badlandsWellRarityPerChunk = 350
netherWellRarityPerChunk = 350
snowWellRarityPerChunk = 350
mossyStoneWellRarityPerChunk = 350
forestWellRarityPerChunk = 350
mushroomWellRarityPerChunk = 350
[RSShipwrecksConfig.blacklist]
blacklistedShipwreckBiomes = ""
addEndShipwreckToModdedBiomes = true
addNetherBricksShipwreckToModdedBiomes = true
addCrimsonShipwreckToModdedBiomes = true
addWarpedShipwreckToModdedBiomes = true
[RSShipwrecksConfig.maxChunkDistance]
endShipwreckMaxChunkDistance = 24
netherBricksShipwreckMaxChunkDistance = 51
crimsonShipwreckMaxChunkDistance = 41
warpedShipwreckMaxChunkDistance = 41
[RSMansionsConfig.blacklist]
blacklistedMansionBiomes = ""
addMansionBirchToModdedBiomes = true
addMansionJungleToModdedBiomes = true
addMansionOakToModdedBiomes = true
addMansionSavannaToModdedBiomes = true
addMansionTaigaToModdedBiomes = true
addMansionDesertToModdedBiomes = true
addMansionSnowyToModdedBiomes = true
[RSMansionsConfig.maxChunkDistance]
mansionBirchMaxChunkDistance = 140
mansionJungleMaxChunkDistance = 140
mansionOakMaxChunkDistance = 140
mansionSavannaMaxChunkDistance = 140
mansionTaigaMaxChunkDistance = 140
mansionDesertMaxChunkDistance = 140
mansionSnowyMaxChunkDistance = 140
[RSWitchHutsConfig.blacklist]
blacklistedWitchHutsBiomes = ""
addWitchHutsOakToModdedBiomes = true
addWitchHutsTaigaToModdedBiomes = true
addWitchHutsBirchToModdedBiomes = true
addWitchHutsDarkForestToModdedBiomes = true
addWitchHutsGiantTreeTaigaToModdedBiomes = true
[RSWitchHutsConfig.maxChunkDistance]
witchHutsOakMaxChunkDistance = 48
witchHutsTaigaMaxChunkDistance = 48
witchHutsBirchMaxChunkDistance = 48
witchHutsDarkForestMaxChunkDistance = 48
witchHutsGiantTreeTaigaMaxChunkDistance = 48
[RSBastionsConfig.blacklist]
blacklistedUndergroundBastionsBiomes = ""
addBastionUndergroundToModdedBiomes = true
[RSBastionsConfig.maxChunkDistance]
bastionUndergroundMaxChunkDistance = 500
