name = "Vanilla+ ServerMinimal"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fe774efc5e6f2d1fcb59460a486db437d190d1938d5e9095798cbd612dbb5e3"

[versions]
fabric = "0.12.12"
minecraft = "1.16.5"
